### ISSUE TITLE
deprecated error

### ISSUE THREAD

**Issue by bhzdcz** [aminkh17/chatup#1]
I got "Deprecated error" and I solve this with following code at line 32 in app.js

``app.use(session({ secret: secret ,
- resave: false,
- saveUninitialized: false
  }));``

Now I get this when run app:

`~\chatup\chatup\node_modules\mongoose\node_modules\mongodb\lib\server.js:242
        process.nextTick(function() { throw err; })
                                                               ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)`

any help ?

**Comment by aminkh17** [comment]
Thank you dear Behzad
Did you install [MongoDB](https://www.mongodb.com/)?

simply run mongod in your command line.

be notice in Windows base systems mongod default folder is [Drive]:\data\db
